Added privKeyToHdWallet() function.
KoinKeep/BitcoinSpoon pull request #5
Opened 2021-08-19 05:04 UTC by dplusplus1024

Added a function to return an HD wallet, given 256 bits of entropy and a passphrase.

2021-08-19 21:18 UTC, ddustin requested changes
Love the name. Needs safety code added. You can see examples of the safety code in other functions in this file.

2021-08-19 21:18 UTC, ddustin commented on code/BTCUtil.c
> +{
Add a `DataTrackPush();` on the first line. This "indents" the ARC scope by one -- it's not strictly needed but doing it allows the functions in this file (that require being inside an ARC scope) to be called by code not in any ARC scope.

2021-08-19 21:18 UTC, ddustin commented on code/BTCUtil.c
> +    return hdWalletPriv(DataCopyDataPart(hash, 0, 32), DataCopyDataPart(hash, 32, 32));
To "unindent" the ARC scope by one, this needs to become `return DTPop(...);` where ... is your hdWalletPriv code.

2021-08-19 21:18 UTC, ddustin commented on code/BTCUtil.c
> +{
Let's add a check here for `if(toMnemonic(privKey).bytes == NULL)` and if it is null return `DTPopNull();`

2021-08-19 21:18 UTC, ddustin commented on code/BTCUtil.c
> +
Before we pull specific indices off `hash`, we should confirm it is at least that big (lest we create a buffer overrun). Add an assert like so `BTCUTILAssert(hash.length == 64);`

2021-08-19 21:18 UTC, ddustin commented on code/BTCUtil.c
> +
After the assert, add another line for safety when asserts are disabled:
`if(hash.length != 64)
return DTPopNull();`

2021-08-20 02:58 UTC, dplusplus1024 commented
Okay, it's been updated with all the safety precautions.

2021-08-20 03:24 UTC, ddustin requested changes
Love it. One last change and it should be perfect 👍

2021-08-20 03:24 UTC, ddustin commented on code/BTCUtil.c
> +    Data hdWallet = hdWalletPriv(DataCopyDataPart(hash, 0, 32), DataCopyDataPart(hash, 32, 32));
This variable name needs to be named something difference since `hdWallet(...)` is already a function name

2021-08-20 03:49 UTC, ddustin approved these changes

2021-08-20 03:49 UTC, merged